[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[build.environment]
  NODE_VERSION = "20"
  
[context.production.environment]
  BUILD_IMAGE = "ubuntu-noble-24.04"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

